
[font]
size = 12.0
# normal = { family = "MesloLGS Nerd Font", style = "Regular" }
normal = { family = "BitstromWera Nerd Font", style = "Regular" }
bold = { family = "BitstromWera Nerd Font", style = "Bold" }
italic = { family = "BitstromWera Nerd Font", style = "Italic" }

[window]
decorations = "None"
dynamic_padding = false
opacity = 0.85
startup_mode = "Maximized"

[window.padding]
x = 5
y = 5

[selection]
save_to_clipboard = true

[general]
live_config_reload = true
ipc_socket = true

[terminal.shell]
program = "/bin/zsh"
# args = [
#     "-l",
#     "-c",
#     "tmux attach || tmux"
#     ]
